source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in galaxy-milky_way.gemspec.
gemspec
gemspec path: "./../galaxy"

gem "puma"

gem "sqlite3"

gem "sprockets-rails"
gem "web-console"

# Start debugger with binding.b [https://github.com/ruby/debug]
# gem "debug", ">= 1.0.0"

gem "view_component"